### ISSUE TITLE
TwoStageFileTransferGUI

### ISSUE THREAD

**Issue by AlbertZhaoz** [knightofnet/TwoStageFileTransfer#2]
Hi, this solution need AryxDevLibrary.dll(latest). We download this repo directly, then this proj doesn't build.
For example:we can't find some type:Logger, if we include aryxdevlibrary.dll from your download link, this dll is missing a lot of properties. Thanks.

**Comment by knightofnet** [comment]
Hi, there,
Thank you for your issue. It is an oversight on my part; I am working on both projects at the same time. But yes, I had not published the new version of AryxDevLibrary on nuget, nor restored its use as a reference.
It's fixed !
